-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 19:12:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`person` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `phone_UNIQUE` ON `mydb`.`person` (`phone` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zip_code` CHAR(5) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `customer_id` INT UNSIGNED NOT NULL,
  `person_id` INT UNSIGNED NOT NULL,
  `address_id` INT UNSIGNED NULL,
  `date_of_birth` DATE NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_customer__person__person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer__address__address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `person_id_UNIQUE` ON `mydb`.`customer` (`person_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `address_id_idx` ON `mydb`.`customer` (`address_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`sales_rep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales_rep` (
  `sales_rep_id` INT UNSIGNED NOT NULL,
  `person_id` INT UNSIGNED NOT NULL,
  `management_region` VARCHAR(20) NULL,
  PRIMARY KEY (`sales_rep_id`),
  CONSTRAINT `fk_sales_rep__person__person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `person_id_UNIQUE` ON `mydb`.`sales_rep` (`person_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT UNSIGNED NOT NULL,
  `status` ENUM('pending', 'completed', 'canceled') NOT NULL DEFAULT 'pending',
  `start_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_order__customer__customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `customer_id_idx` ON `mydb`.`order` (`customer_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_category` (
  `product_category_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`product_category_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(16,4) NOT NULL,
  `stock` INT NOT NULL,
  `product_category_id` INT UNSIGNED NOT NULL,
  `discount` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `discription` VARCHAR(200) NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product__product_category__product_category_id`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `mydb`.`product_category` (`product_category_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `product_category_id_idx` ON `mydb`.`product` (`product_category_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campaign` (
  `campaign_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `budget` DECIMAL(16,4) NOT NULL,
  `discription` VARCHAR(200) NULL,
  PRIMARY KEY (`campaign_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`customer_interaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_interaction` (
  `customer_interaction_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT UNSIGNED NOT NULL,
  `sales_rep_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `type` ENUM('phone call', 'email', 'meeting') NOT NULL,
  `details` VARCHAR(200) NOT NULL,
  `outcome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`customer_interaction_id`),
  CONSTRAINT `fk_customer_interaction__customer__customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_interaction__sales_rep__sales_rep_id`
    FOREIGN KEY (`sales_rep_id`)
    REFERENCES `mydb`.`sales_rep` (`sales_rep_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `customer_id_idx` ON `mydb`.`customer_interaction` (`customer_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `sales_rep_id_idx` ON `mydb`.`customer_interaction` (`sales_rep_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`connection` (
  `person_id_1` INT UNSIGNED NOT NULL,
  `person_id_2` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`person_id_1`, `person_id_2`),
  CONSTRAINT `fk_contact__person__person_id`
    FOREIGN KEY (`person_id_1`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact__persson__person_id_2`
    FOREIGN KEY (`person_id_2`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `person_id_2_idx` ON `mydb`.`connection` (`person_id_2` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  CONSTRAINT `fk_purchase__order__order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase__product__product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `product_id_idx` ON `mydb`.`purchase` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
